### ISSUE TITLE
Display problem - ON/OFF

### ISSUE THREAD

**Issue by truefriend-cz** [zeelog/OTA#23]
Hello, i have problem.

after switching off the display with the button, the display remains switched off for only a few minutes and then lights up on its own for a few seconds, then goes out, then lights up again and so on. The display wake-up is not based on an arrival or an application activity. This problem also occurs with a newly installed system after installing another default Launcher (Nova Launcher).

Tested on Image: lineage-18.1-20201226-UNOFFICIAL-mido

**Comment by anandsvm** [comment]
Never faced this issues nor any users reportrd.. Check with all default settings and apps if issue persists. ( Update your firmware too)

**Comment by Dreamdance61** [comment]
Had  the same problem with two devices (beginning with build 20201230 up to 20210216, Magisk + modules systemless hosts / Nanodroid-microg / Nanodroid-fdroid / spoof_ADVDAPI30).

Symptom: high battery consumption because of display-on-time. 
Temporary solution: Everytime I switched off via double tap the display stayed off.
 
Digging in the log i found many wakeup-entrys with REASON_WAKE_GESTURE.

The solution for me was to explicitly switch off the complete section
  Settings -> Display -> Advanced -> Lock Screen -> InactivityDisplay
(no suboption was checked there)

Now I'am happy with an super stable rom with low power comsumption of 0.5% per hour.
